#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 11 14:29:42 2021

@author: jyoti
"""

import torch

t = torch.tensor([[1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3]], dtype = torch.float32)

print(t.size())
print(t.shape)

print(len(t.shape)) # rank of the tensor
print(t.numel()) #number of components in a tensor

#RESHAPING a tensor, we can reshape the tensor to any shape regarded that number of elements is the tensor does not change
print(t.reshape(12,1)) # change in shape but nnot in change in dimensions
print(t.reshape([12,1]))
#print(t.reshape(12,1,1))#change in shape with the number of dimensions

#we can change the shape by squeezing and unsqeezing the tensors as well
#squeezing the tensor removes the dimensions or axes that have a length of one
#unsqueezing the tensor adds the dimensions with a length of 1

print(t.reshape([12,1]).squeeze())
print(t.reshape([12,1]).squeeze().shape)

print(t.reshape([12,1]).unsqueeze(dim =0))
print(t.reshape([12,1]).unsqueeze(dim =1).shape)